exemple: exemple.cpp
	g++ -I /usr/local/include/eigen -Wall -o exemple exemple.cpp 

linearInt: linearInt.cpp
	g++ -I /usr/local/include/eigen -Wall -o linearInt linearInt.cpp 

main_spline: main_spline.cpp spline.hpp
	g++ -I /usr/local/include/eigen -Wall -o main_spline main_spline.cpp 